name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente à meia-noite UTC
  workflow_dispatch: # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Garantir que a branch 'output' existe
        run: |
          if ! git ls-remote --exit-code --heads origin output; then
            git checkout --orphan output
            git commit --allow-empty -m "Initial commit on output branch"
            git push origin output
          fi

      - name: Remover arquivos conflitantes
        run: rm -f dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg

      - name: Gerar animação do Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: Aipalit
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e push do SVG gerado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualização automática do Snake Game"
          branch: output
          file_pattern: dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg
